swagger: "2.0"
info:
  description: "CliqMind Account Management Service"
  version: "1.0.0"
  title: "Account Management Service"
  termsOfService: "http://cliqmind.ir/terms/"
  contact:
    email: "info@cliqmind.ir"
  
    
host: "127.0.0.1"
basePath: "/api/v1"
tags:
- name: "transaction"
  description: "Add Transaction"
schemes:
- "https"
- "http"
paths:
  /transaction/add:
    post:
      tags:
      - "transaction"
      summary: "Add Transaction"
      description: "This can only be done by the unknown user."
      operationId: "addTransaction"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "add transaction object"
        required: true
        schema:
          $ref: "#/definitions/Transaction"
      responses:
        "200":
          description: "successful transaction added"
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: "Invalid request format "
        "401":
          description: "Invalid credential"
  
  /transaction/rollback:
    post:
      tags:
      - "transaction"
      summary: "Rollback Transaction"
      description: "This can only be done by the unknown user."
      operationId: "rollbackTransaction"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "rollback transaction object"
        required: true
        schema:
          $ref: "#/definitions/RollbackTransaction"
      responses:
        "200":
          description: "successful transaction added"
          schema:
            $ref: "#/definitions/ResponseMessage"
        "400":
          description: "Invalid request format "
        "401":
          description: "Invalid credential"
  
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Transaction:
    type: "object"
    properties:
      id:
        type: "string"
      user_id:
        type: "string"
      is_deposit:
        type: "boolean"
      amount:
        type: "number"
      currency:
        type: "string"
      transaction_code:
        type: "string"
      type:
        type: "string"
  RollbackTransaction:
    type: "object"
    properties:
      id:
        type: "number"
      done_by_user_id:
        type: "string"
      description:
        type: "string"
  ResponseMessage:
    type: "object"
    properties:
      result:
        type: "string"
      message:
        type: "string"

        
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"