/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.17).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ir.cliqmind.am.api;

import ir.cliqmind.am.dto.GenerateCouponCodeResponse;
import ir.cliqmind.am.dto.GetCouponsRequest;
import ir.cliqmind.am.dto.GetCouponsResponse;
import ir.cliqmind.am.dto.ResponseMessage;
import ir.cliqmind.am.dto.UpsertCouponRequest;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-11-08T17:36:36.325Z")

@Api(value = "coupon", description = "the coupon API")
@RequestMapping(value = "/api/v1")
public interface CouponApi {

    @ApiOperation(value = "Add Coupon", nickname = "addCoupon", notes = "This can only be done by the unknown user.", response = ResponseMessage.class, tags={ "coupon", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful coupon added", response = ResponseMessage.class),
        @ApiResponse(code = 400, message = "Invalid request format "),
        @ApiResponse(code = 401, message = "Authorization error") })
    @RequestMapping(value = "/coupon/add",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<ResponseMessage> addCoupon(@ApiParam(value = "add coupon" ,required=true )  @Valid @RequestBody UpsertCouponRequest body);


    @ApiOperation(value = "Edit Coupon", nickname = "editCoupon", notes = "This can only be done by the unknown user.", response = ResponseMessage.class, tags={ "coupon", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful coupon edition", response = ResponseMessage.class),
        @ApiResponse(code = 400, message = "Invalid request format "),
        @ApiResponse(code = 401, message = "Authorization error") })
    @RequestMapping(value = "/coupon/edit",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<ResponseMessage> editCoupon(@ApiParam(value = "edit coupon" ,required=true )  @Valid @RequestBody UpsertCouponRequest body);


    @ApiOperation(value = "Generate Coupon Code", nickname = "generateCouponCode", notes = "This can only be done by the unknown user.", response = GenerateCouponCodeResponse.class, tags={ "coupon", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful coupon code returned", response = GenerateCouponCodeResponse.class),
        @ApiResponse(code = 400, message = "Invalid request format "),
        @ApiResponse(code = 401, message = "Authorization error") })
    @RequestMapping(value = "/coupon/generate",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<GenerateCouponCodeResponse> generateCouponCode();


    @ApiOperation(value = "Get Coupons", nickname = "getCoupons", notes = "This can only be done by the unknown user.", response = GetCouponsResponse.class, tags={ "coupon", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful coupons returned", response = GetCouponsResponse.class),
        @ApiResponse(code = 400, message = "Invalid request format "),
        @ApiResponse(code = 401, message = "Authorization error") })
    @RequestMapping(value = "/coupon/get",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<GetCouponsResponse> getCoupons(@ApiParam(value = "get coupons" ,required=true )  @Valid @RequestBody GetCouponsRequest body);

}
